### ISSUE TITLE
Product specification: Authorisation

### ISSUE THREAD

**Issue by heuels** [briskhome/briskhome#105]
## Product specification: Authorisation
User authorisation in BRISKHOME should be based on session mechanics. Sessions should have an expiration date set to 1 year in the future and prolong automatically upon reaching a middle point between date of issue (prolongation) and date of expiry.

JSON Web Tokens should be used to hold session information, both client side and server side. Example payload of such JWT:
```json
{
  "iss": "BRISKHOME",
  "sub": "testuser",
  "azp": "device_uuid",
  "aud": "server_uuid // certificate fingerprint base64'd",
  "iat": "1433978353",
  "exp": "1433981953",

  "email": "testuser@gmail.com",
  "name" : "Test User"
}
```

The application should have an open section (with *onboarding* and *access-denied* pages) and a closed section (containing the webapp itself). When an unauthorised user attempts to access the closed section they should be redirected to *access-denied* page.

#### Update: Session considerations
1. Using JWT for sessions is an overkill. Why? Because even if we used JWT we still would query the database each time to deserialize user from JWT payload.
2. We should use long unique strings (tokens) for sessions. When a session is issued it should be linked to a particular user with all relevant information like browser fingerprint, device name etc.
3. JWT tokens are great for passing signed data between parties. In our scenario we only have one party. So I guess using random strings for tokens is good enough.
---
#### Use sessions in web application – _6 tasks_
  - [x] feat(core.config): support nested configuration via environment variables (#151)
  - [x] feat(core.webapp): add mongo-based sessions (#106)
  - [x] feat(core.webapp): add unauthorised section (#125)
  - [x] feat(core.webapp): display logged in user info in the interface (#128)
  - [ ] feat(core.webapp): serve closed section of the webapp via HTTPS
  - [ ] feat(core.pki): generate self-signed root certificate on install

#### User section – _1 task_
  - [x] feat(core.webapp): display all active sessions and allow session revokation (#136)

#### User widget – _2 tasks_
  _Tasks from this section were not in a current scope._

#### Login and Onboarding (Initial registration) – _4 tasks_
  - [x] ~~feat(core.config): implement saving updated plugin configuration (#54)~~
  _This was meant to provide a base for disabling the onboarding page._
  - [x] feat(core.webapp): disable onboarding when initial setup is complete (#145)
  - [x] feat(core.webapp): add login page (#118)
  - [x] feat(core.webapp): add onboarding page (#145)
  - [x] test(core.webapp): end-to-end tests (#129)

#### Documentation – _1 task_
  - [ ] docs(core.webapp): describe user authorisation

**Comment by heuels** [comment]
While using sessions for user authentication is sufficient a problem of user authorisation (especially checking permissions) still stands. One of the options for authorisation is presented in [this repo](https://github.com/chenkie/graphql-auth) and it requires almost no additional actions from a client.
