### ISSUE TITLE
Custom component loader

### ISSUE THREAD

**Issue by heuels** [briskhome/briskhome#38]
Currently in order to support plugins **Briskhome** uses c9/architect. This is a great module and it provided the exact functionality the application needed throughout its development cycle. Now it is time to fork it to catch up with our aspirations.

To create the application instance with **architect** the following steps are performed:

```javascript
// Composing a list of components that should be loaded
const architect = require('architect');
const enabledComponents = require('./components').enabledComponents();
const components = architect.resolveConfig(enabledComponents, path.resolve(__dirname))
architect.createApp(components, (err, app) => {
  ...
});
```

The target flow with the new application loader should be quite similar:

```javascript
import Architect, { resolveConfig, enabledPlugins } from './architect';
(async () => {
  const plugins = await resolveConfig(enabledPlugins(), path.resolve(__dirname, '..');
  const app = await new Architect().load(plugins);
})();
```

This is a draft of the specification for the custom application loader. Some of the features mentioned below may or may not be included in the final version of the application loader.

### Specification

- ~~Plugins should be divided into two groups: **core** plugins and **additional** plugins.~~

  - ~~**Core plugins** are application itself. They provide the core functionality and without them the application would be non operational or highly unstable.~~
  - ~~**Additional plugins** provide *additional* functionality and are not developed as a part of the application.~~

  ~~By default core plugins are loaded from `./lib` directory and additional plugins are loaded from `./node_modules` directory. There should be a configuration option to change this.~~

- The application loader should support enabling and disabling plugins by calling their `.enable()` and `.disable()` methods (the original **architect** module supports disabling by calling `.onDestroy()` method).

### Roadmap

_See [this comment](/briskhome/briskhome/issues/38#issuecomment-303355019) for progress updates._
- [x] **Rewrite original architect with ES6 and Flow**.
      The application loader should use Flow static type checking and modern JavaScript syntax. Use of async/await is preferred over callbacks and plain promises.
- [x] **Unit tests and bugfixes**.
      All functions of the application loader should be unit tested with **Jest**. 
- [ ] **Optimise performance**.
      The application loader should be quicker that original [c9/architect](/c9/architect).
- [x] **Use default ~~and named~~ exports**.
      The application loader should be able to resolve provided services from ~~named exports. If there is only one provided service and no named exports present, use~~ default export.
- [ ] **Exposing plugin list**.
      A list of plugins with lists of resources they provide (see #43) should be available via GraphQL so that it is possible to display it in the web application. 
- [ ] **Intergrate enabling and disabling plugins**. 
      See #36.
- [x] **Allow customisation of configuration key**.
      The key that is used to determine required `package.json` fields should be customisable.
- [x] **Loading even if one of plugins failed to start**.
      If the plugin is not consumed by any other plugin then it should be disabled, skipped and the failure event should be logged at the end of the init cycle. Additional plugins should not interfere with core loading and functionality.
- [ ] **Runtime plugin manipulation**.
      ~~There should be a way of specifying which plugins are **core** (the ones that generally can't be disabled) and which are additional (the ones that can be disabled both in runtime and offline).~~ A handler to reload configuration or enable/disable additional plugins should be present.
- [x] **Built-in configuration loader**. 
      Currently **architect** passes `options` object into every component it loads, but that object stays empty because **Briskhome** plugins receive configuration from **core.config** component via `imports` object. Providing configuration to plugins should be performed by the application loader via `options` object **or** by providing a hook to insert configuration.
- [x] **Plugin loading timeout**.
      Currently if a plugin fails to call `register` callback the application waits for it endlessly. This should be fixed so that plugins have several seconds to load or otherwise timeout error would be thrown.

**Comment by heuels** [comment]
It also needs to use default exports from components instead of named `setup` export, since this is usually the only thing being exported from the component.

**Comment by heuels** [comment]
### 1. Rewrite original architect with ES6 and Flow.
> The application loader should use Flow static type checking and modern JavaScript syntax. Use of async/await is preferred over callbacks and plain promises.
- This also removes AMD support and thus decreases code duplication.
- Need to fix a lot of Flow errors.

### 2. Unit tests and bugfixes.
> All functions of the application loader should be unit tested with Jest.
* Two types of tests should be prepared: normal unit tests and regression tests against the original architect to verify that the functionality was not broken. Note that API will be different and two modules should not be compared directly, but by result!

**Comment by heuels** [comment]
The above-referenced pull request implements custom plugin loader that is based off **architect**. While it still lacks several features it still will be merged. Some of those features like exposing plugin lists, runtime plugin manipulation and updating the destructor mechanics will be coded separately.
